import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Input from "../app/(Welcomeerror)/Input";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const navbar :{id:number,name:string,href:string}[]=[
  {
    id: 1,
    name:"Home",
    href:"/"
  },
  {
    id: 2,
    name:"Log-In",
    href:"/login"
  },
  {
    id: 3,
    name:"Register",
    href:"/register"
  },
  {
    id: 4,
    name:"Forgot-Password",
    href:"/forgot-pwd"
  }
  ,
  {
    id: 5,
    name:"Photos",
    href:"/Photo"
  }
  ,
  {
    id: 6,
    name:"Animals",
    href:"/animal"
  },{
    id: 7,
    name:"Posts",
    href:"/post"
  },
  
]

export const metadata: Metadata = {
  // prefix  : pishrukh nam page
  // postfix: az pusht sar nam page
  title: {
    default:"Defult",
    // template:"%s | Mahjabin"
    template:"Mahjabin | %s"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
      <nav className="h-[30px] w-full justify-between items-center p-8 m-8m flex bg-gray-500 text-white "
          >
            
            {navbar.map(nav=>{
              return<Link key={nav.id} href={nav.href}>{nav.name}</Link>
            })}
                        </nav>     
    <h1>{children}</h1>

      </body> 
    </html>
  );

}